### ISSUE TITLE
ikev2 issue

### ISSUE THREAD

**Issue by fxs007** [ftao/vpn-deploy-playbook#135] opened 2017-01-14 05:54 UTC
Does the following picture mean ikev2_users needs to be set env? In my test, I did not set and export ikev2_users in shell, and my ansible failed. 
<img width="652" alt="screen shot 2017-01-14 at 1 50 15 pm" src="https://cloud.githubusercontent.com/assets/2969802/21952799/468a95da-da60-11e6-9b69-be4b2d758fd7.png">

I have a patch, which I think can fix the issue. Can I push the complete patch?
diff --git a/roles/strongswan/tasks/ios8.yml b/roles/strongswan/tasks/ios8.yml
index 5fc3c0b..276b1e2 100644
--- a/roles/strongswan/tasks/ios8.yml
+++ b/roles/strongswan/tasks/ios8.yml
@@ -18,9 +18,14 @@
     - ipsec
     - ios8

+- debug: msg='ikev2_users = {{ ikev2_users }} '
+
+- debug: msg="item.username = {{ item.username }}"
+  with_items: "{{ ikev2_users }}"
+
 - name: generate ios config files
   template: src=ios8-profile.mobileconfig dest=/var/www/ikev2/ios8-profile/{{ item.username }}.mobileconfig
-  with_items: ikev2_users
+  with_items: "{{ ikev2_users }}"
   tags:
     - ipsec
     - ios8

**Comment by ftao** [comment] 2017-01-14 13:02
Sure, send a pull request . 
That's new syntax required by newer version of ansible .

**Comment by ftao** [comment] 2017-07-27 11:32
the issue is resolved by https://github.com/ftao/vpn-deploy-playbook/pull/136

**Closed by ftao** 2017-07-27 11:32 UTC
